//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErSoftDev.Identity.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IdentityTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IdentityTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErSoftDev.Identity.Domain.Resources.IdentityTranslate", typeof(IdentityTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل یکی از اطلاعات آدرس باید  پر شود یا هیچکدام پر نشود.
        /// </summary>
        internal static string AllFieldsOfAddressMustBeFillOrNonOfFields {
            get {
                return ResourceManager.GetString("AllFieldsOfAddressMustBeFillOrNonOfFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل یکی از مقادیر مرورگر یا نام دستگاه باید پر شود.
        /// </summary>
        internal static string OneOfTheBrowserOrDeviceNameMustBeFill {
            get {
                return ResourceManager.GetString("OneOfTheBrowserOrDeviceNameMustBeFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز ها یکسان نمی باشد.
        /// </summary>
        internal static string PasswordsAreNotEqual {
            get {
                return ResourceManager.GetString("PasswordsAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفرش توکن غیر فعال می باشد.
        /// </summary>
        internal static string RefreshTokenIsDeActive {
            get {
                return ResourceManager.GetString("RefreshTokenIsDeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفرش توکن منقضی شده است.
        /// </summary>
        internal static string RefreshTokenIsExpire {
            get {
                return ResourceManager.GetString("RefreshTokenIsExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفرش توکن لغو شده است.
        /// </summary>
        internal static string RefreshTokenIsRevoked {
            get {
                return ResourceManager.GetString("RefreshTokenIsRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفرش توکن استفاده شده است.
        /// </summary>
        internal static string RefreshTokenIsUsed {
            get {
                return ResourceManager.GetString("RefreshTokenIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تست.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر فعال نمی باشد.
        /// </summary>
        internal static string UserIsNotActive {
            get {
                return ResourceManager.GetString("UserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور صحیح نمی باشد.
        /// </summary>
        internal static string UsernameOrPasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
