version : '3.1'

services : 
    elasticsearch : 
        container_name : elasticsearch
        image : docker.elastic.co/elasticsearch/elasticsearch:8.7.1
        ports : 
            - 9200:9200
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        environment : 
            - xpack.security.enabled=false
            - discovery.type=single-node
        networks : 
            - elastic

    kibana :
        container_name : kibbana
        image : docker.elastic.co/kibana/kibana:8.7.1
        ports : 
            - 5601:5601
        depends_on :
            - elasticsearch
        environment : 
            - ELASTICSEARCH_URL=http://localhost:9200
        networks : 
            - elastic

    redis:
        container_name: redis
        image: redis:latest
        restart: always
        volumes:
            - redis_volume_data:/data
        ports:
            - 6379:6379
            
    rabbitmq:
        container_name: rabbitMq
        image: rabbitmq:3-management
        restart: always
        ports:
            - 15672:15672
            - 5672:5672
            
    jaeger:
        container_name: jaeger
        image: jaegertracing/all-in-one:latest    
        restart: always
        ports:
            - 16686:16686
            - 5775:5775
            
    consul:
        container_name: consul
        image: consul:1.15.4    
        restart: always
        ports:
            - 8500:8500
            
            
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=${Sa_Password:-1Secure*Password1}
        - MSSQL_PID=Developer
        ports:
        - 1433:1433
        restart: always
        
    mongo:
        image: mongo
        restart: always
            
networks : 
    elastic :
        driver : bridge

volumes : 
    elasticsearch-data :
    redis_volume_data:


        