//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErSoftDev.DomainSeedWork.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedTranslate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedTranslate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ErSoftDev.DomainSeedWork.Resources.SharedTranslate", typeof(SharedTranslate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یا همه ی  فیلد های آدرس باید پر شوند یا هیچکدام از آنها.
        /// </summary>
        internal static string AllFieldsOfAddressMustBeFillOrNonOfFields {
            get {
                return ResourceManager.GetString("AllFieldsOfAddressMustBeFillOrNonOfFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با مشخصات ارسالی قبلا رکوردی در دیتابیس ذخیره شده است.
        /// </summary>
        internal static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکی از پارامتر های ارسالی ایراد دارد.
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در دیتابیس رخ داده است.
        /// </summary>
        internal static string DbError {
            get {
                return ResourceManager.GetString("DbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در انجام عملیات.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای منطقی رخ داده است.
        /// </summary>
        internal static string LogicError {
            get {
                return ResourceManager.GetString("LogicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکوردی یافت نشد.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل یکی از مقادیر مرورگر یا نام دستگاه باید پر شود.
        /// </summary>
        internal static string OneOfTheBrowserOrDeviceNameMustBeFill {
            get {
                return ResourceManager.GetString("OneOfTheBrowserOrDeviceNameMustBeFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامتر های ارسالی معتبر نمی باشد.
        /// </summary>
        internal static string ParametersAreNotValid {
            get {
                return ResourceManager.GetString("ParametersAreNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز های عبور یکسان نمی باشند.
        /// </summary>
        internal static string PasswordsAreNotEqual {
            get {
                return ResourceManager.GetString("PasswordsAreNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ProcessingIsInProgress {
            get {
                return ResourceManager.GetString("ProcessingIsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس دهنده در دسترسی نمی باشد.
        /// </summary>
        internal static string ProviderNotAvailable {
            get {
                return ResourceManager.GetString("ProviderNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفرش توکن غیر فعال می باشد.
        /// </summary>
        internal static string RefreshTokenIsDeActive {
            get {
                return ResourceManager.GetString("RefreshTokenIsDeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان استفاده از رفرش توکن منقضی شده است.
        /// </summary>
        internal static string RefreshTokenIsExpire {
            get {
                return ResourceManager.GetString("RefreshTokenIsExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفرش توکن باطل شده است.
        /// </summary>
        internal static string RefreshTokenIsRevoked {
            get {
                return ResourceManager.GetString("RefreshTokenIsRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفرش توکن قبلا استفاده شده است.
        /// </summary>
        internal static string RefreshTokenIsUsed {
            get {
                return ResourceManager.GetString("RefreshTokenIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست ارسال شده فاقد توکن می باشد.
        /// </summary>
        internal static string RequestHasNotToken {
            get {
                return ResourceManager.GetString("RequestHasNotToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه امنیتی داخل توکن معتبر نمی باشد.
        /// </summary>
        internal static string SecurityStampTokenIsNotValid {
            get {
                return ResourceManager.GetString("SecurityStampTokenIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد .
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات توکن ناقص می باشد.
        /// </summary>
        internal static string TokenHasNotClaim {
            get {
                return ResourceManager.GetString("TokenHasNotClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضای توکن فرا رسیده است ، جهت دریافت توکن جدید میتوانید از سرویس های  گت توکن یا رفرش توکن استفاده نمایید..
        /// </summary>
        internal static string TokenIsExpired {
            get {
                return ResourceManager.GetString("TokenIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن امن فاقد مهر امنیتی می باشد.
        /// </summary>
        internal static string TokenIsNotSafeWithSecurityStamp {
            get {
                return ResourceManager.GetString("TokenIsNotSafeWithSecurityStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن معتبر نمی باشد.
        /// </summary>
        internal static string TokenIsNotValid {
            get {
                return ResourceManager.GetString("TokenIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی وجود ندارد.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای پیش بینی نشده ای اتفاق افتاده است.
        /// </summary>
        internal static string UnhandledExceptionHappened {
            get {
                return ResourceManager.GetString("UnhandledExceptionHappened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تراکنش نامشخص می باشد.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        internal static string UsernameOrPasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("UsernameOrPasswordIsNotCorrect", resourceCulture);
            }
        }
    }
}
